### ISSUE TITLE
DooyaRemoteDevice should extend end.devices.ShutterController

### ISSUE THREAD

**Issue by michbeck100** [codedealer/pimatic-dooya#1]
As the DooyaRemoteDevice is controlling a shutter it should extend the correct device. This way it will be recognized as such by plugins like pimatic-hap. See https://forum.pimatic.org/topic/4857/pimatic-dooya-dooya-dc-retractable-sunshade-awning-cover/2

**Comment by codedealer** [comment]
Thank you for your contribution! PR was merged and I bumped the npm version.
